### PR TITLE
feat : Added Issue templates and PR templates

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR is for the issue no #3048

This PR Contains

* Added Issues Templates
* Added PR Templates

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @linggao

**Comment by Ayush7614** [comment]
cc @joewxboy

**Comment by joewxboy** [comment]
@Ayush7614 Please link this PR to the related issue and add `Issue: ## - ` to the beginning of the PR's title.

**Comment by Ayush7614** [comment]
cc : @joewxboy

**Comment by Ayush7614** [comment]
cc @joewxboy @dabooz

**Review by joewxboy — APPROVED** [review]
Thanks.  These files are technically sound.  They will add options when opening a new issue or creating a PR.  I cannot speak to the contents of these templates.  The team will have to review that and adjust as needed.

**Pull request merged**
