### PR TITLE
issue 2435 - Updating anax/test README file

### PR DESCRIPTION
**Pull request by Al-tekreeti**
Signed-off-by: Mustafa <mmaj1976@gmail.com>

### CODE REVIEW

**Review by linggao — COMMENTED** [review]
I approve the README.md part. @bmpotter could you make sure edgeNodeFiles.sh  part is correct? thanks.

**Comment by linggao** [comment]
@Al-tekreeti could you please resolve the conflict file README.md?

**Comment by Al-tekreeti** [comment]
could you share the path for edgeNodeFiles.sh. I cannot find it in `anax/test/gov`

**Comment by Al-tekreeti** [comment]
I doubled checked edgeNodeFiles.sh, nothing to worry about.

**Review by linggao — APPROVED** [review]

**Pull request merged**
