### PR TITLE
Issue3852 ubi92rebase

### LINKED ISSUE #3852: Feature Request: Update container images to latest UBI baseimage
### Is your feature request related to a problem? Please describe.

We should update all container images to UBI 9.2 to pull in security fixes and other updates. 

### Describe the solution you'd like.

Currently we are using UBI 9.1. There is a newer version, 9.2 available for all architectures (amd64, arm64, ppc64le, s390x). The Dockerfiles should change to `FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2`.

### Describe alternatives you've considered

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by johnwalicki**
# Pull Request Template

## Description

Fixes #3852 

- Issue #3852 - Remove unused DOCKER_VER argument from Dockerfile_agbot.ubi
- Issue #3852 - Bump to Docker Engine version 24.0.5
- Issue #3852 - Update container images to UBI 9.2

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

I don't have the infrastructure to test these changes.  After the build process, this should be tested.
 
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by bencourliss** [comment]
@johnwalicki I noticed you didn't include ppc64le in the Dockerfile updates. UBI9.2 exists for that architecture, https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b?architecture=ppc64le

**Comment by johnwalicki** [comment]
@bencourliss  Several months ago, we had to revert back to the ubi8.7 images for ppc because Open Horizon didn't have an internal IBM build pipeline / test environment that was running RHEL 9.x for those architectures.   I don't have visibility to that any longer.

I would be happy to increment the ppc64el / s390x containers if we can.

@dlarson04 can also likely give us guidance.

**Comment by bencourliss** [comment]
@johnwalicki ah ok, that rings bells for me now. Open Horizon is no longer depending on IBM Jenkins for builds as that has been moved into GitHub Actions just recently. We had an intern who did a lot of great work there (shout-out to @blakep7). Specifically he utilized the https://github.com/uraimo/run-on-arch-action GitHub Action runner to allow us to build on armv6, armv7, aarch64, s390x, ppc64le using QEMU.

**Comment by johnwalicki** [comment]
If we want to review / merge this PR, and then observe the GitHub Actions that @blakep7 created, let's see what happens.  

Building containers is the first step.  Testing is a bit more complex.

**Comment by bencourliss** [comment]
@johnwalicki This is probably a discussion and work for another issue, but since you updated Docker for the other images, I was wondering if we could do the same for s390x and ppc64le? It doesn't exist in the same way that it does for the other architectures, but you could install the Centos RPMs and do that. I'll open a new issue for upgrading Docker for those platforms.

**Pull request merged**
