### PR TITLE
Issue 2765 - Added validation for org before create & deletion

### LINKED ISSUE #2765: 'Organization ID contains invalid characters' error after the org is created
Got error when creating an org using super user authority.  The org is created by failed at other calls with `Organization ID contains invalid characters`.  This error should be reported before creating the org. 
````
hzn exchange org create "ling test" -d "my test org"  --max-nodes 5 -u root/superuser1:superuser1
Organization ling test is successfully added to the Exchange.
Agbot IBM/agbot is responsible for deploying services in org ling test
Error: bad HTTP code 400 from PUT https://cp-console.roks-stg-local-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css/api/v1/organizations/ling test: Organization ID (ling test) contains invalid characters
````
Debug shows that the error is from MMS. 
````
[verbose] The model management service url: https://cp-console.roks-stg-local-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css
[verbose] PUT https://cp-console.roks-stg-local-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css/api/v1/organizations/ling test
[verbose] HTTP request timeout set to 30 seconds
[verbose] HTTP code: 400
Error: bad HTTP code 400 from PUT https://cp-console.roks-stg-local-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css/api/v1/organizations/ling test: Organization ID (ling test) contains invalid characters
````
Same problem for org deletion. It seems that the exchange API and the CSS API have different standard for org IDs. 
````
hzn exchange org remove "ling test"  -u root/superuser1:superuser1
Warning: this will also delete all Exchange resources owned by this org (nodes, services, patterns, etc). Are you sure you want to remove org ling test from the Horizon Exchange and the MMS? [y/N]: y
Org ling test is deleted from the Horizon Exchange
Error: bad HTTP code 400 from DELETE https://cp-console.roks-stg-local-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css/api/v1/organizations/ling test
````
Implementation note: 
We have documented that "An organization name cannot contain underscores (_), comas (,), blank spaces ( ), single quotes ('), or question marks (?)."
 In `hzn exchange org create` we should give error when these character are used for org.

### PR DESCRIPTION
**Pull request by dipesh-rawat**
# Pull Request Template

## Description

Added checks to verify that Organization doesn't contains invalid characters: underscores (_), comas (,), blank spaces ( ), single quotes ('), or question marks (?)."

Fixes #2765

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested the regex with combination of all the valid and invalid strings to see the expected outcome.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@johnwalicki Could you please review my changes and let me know if anything needs improving.

**Review by johnwalicki — CHANGES_REQUESTED** [review]
This looks good.  Maybe for style points, make these three changes:
- I would recommend removing the extra whitespace lines in the import() section.
- Spelling of `comas` in the comment should be `commas `
- Indentation style is one char, not a full tab.

**Review by johnwalicki — COMMENTED** [review]
Maybe the indentation is a GitHub patch review thing... ?

**Review by johnwalicki — COMMENTED** [review]
Ignore my indentation request.  VSCode is playing games with me.

**Comment by johnwalicki** [comment]
Can you also change the commit message to include the issue number?
`git commit -s --amend`
change the message to "Issue #2765 Added validation for org before create & deletion"

**Comment by dipesh-rawat** [comment]
@johnwalicki Thanks for the feedback. Have incorporated them in the latest commit.

**Review by johnwalicki — DISMISSED** [review]
LGTM

**Comment by johnwalicki** [comment]
@linggao Can you also look at this PR? I think it's ready to merge.

**Review by linggao — CHANGES_REQUESTED** [review]
Thanks for the fix. 
1. As a common practice in anax, please add the issue number in the commit message.  For example:  'Issue 2765 - Added validation for org before create & deletion". 
2. Please add a unit test case for function ValidateOrg. (I know there are a lot of functions in anax needs unit test cases. ) Please check https://github.com/open-horizon/anax/blob/master/cutil/cutil_test.go to see how unit test cases are written. Then run `make check` to test all the unit test cases.
3. Maybe you did it already, please run `make format` to let the code be auto formatted before checking in the code.

**Comment by dipesh-rawat** [comment]
@linggao Thanks for the feedback. I have made the suggested changes.  Could you please review them.

**Review by johnwalicki — APPROVED** [review]
Approved

**Pull request merged**
