### PR TITLE
1 feature request docker dev env in a box

### PR DESCRIPTION
**Pull request by Demopans**
# Pull Request Template

## Description

Added basic dockerized dev env in dockerDev folder with default settings, tested with Jetbrains Gateway, should work with VSCode's remote development. Intended to speed up onboarding for RCOS students where only said folder need to be provided without needing to kerfuffle with dualbooting, system settings and the like. Only requires Docker Desktop for Windows users.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Use of remote development option that comes shipped with Intellij

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by joewxboy** [comment]
@Demopans Is this PR linked to an open issue?

**Comment by Demopans** [comment]
> @Demopans Is this PR linked to an open issue?

No. This is more something that I figured would be helpful to future RCOS semesters in an attempt to speed up the glacial onboarding process that seems to be common with external projects

**Comment by joewxboy** [comment]
No problem with the idea.  We just require an issue for every PR.  If you could open an issue that briefly describes the problem you are solving in a sentence or two, and then link the PR to the issue, we can continue. Thanks

**Comment by Demopans** [comment]
https://github.com/open-horizon/anax/issues/3753

**Comment by Demopans** [comment]
Do note this is still being worked on

**Comment by joewxboy** [comment]
> Do note this is still being worked on

I'll check.

**Pull request closed without merging**
