### PR TITLE
Issue #3570 - Bug: Support unicode for extended alphabets in constrai…

### PR DESCRIPTION
**Pull request by MaxMcAdam**
…nt language

Signed-off-by: Max McAdam <max@fredcom.com>

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by johnwalicki** [comment]
I have no way to test this.  Will decline to review until we can formally test.

**Comment by davidyao19** [comment]
Jing Jing Pan and Zheng Li are looking into it and will help on verifying it.

**Comment by lizheng2017** [comment]
Jing Jing Pan verified this fix in OH 2.30 env. @davidyao19 FYI

**Comment by jjpanmomok** [comment]
@johnwalicki 
here's my verify step:
1. setup an all in one OH env
2. recreate the issue on the env: when try to add deployment policy with Chinese, it will fail
Screen Shot 2022-12-28 at 16 43 11
3. build anax and hzn on branch pr/3571
4. stop OH service and replace anax and hzn in the OH env
5. start OH service and verify hzn and anax is replaced
Screen Shot 2022-12-28 at 17 39 42
6. add deployment policy with Chinese, this time it succeed
Screen Shot 2022-12-28 at 16 46 44
7. register node with chinese property and verify agreement can be created
Screen Shot 2022-12-28 at 17 56 51

**Comment by johnwalicki** [comment]
@jjpanmomok @lizheng2017  Thanks for verifying that Unicode constraints are valid.
Nice work @MaxMcAdam 
Merging PR.

**Pull request merged**
